### PR TITLE
Margin search button

### LINKED ISSUE #170: Margin for search button
Screenshot from 2020-08-07 18-30-26
Would expect 9px margin like the other buttons in navbar

### PR DESCRIPTION
**Pull request by axel1200**
Fixes #170

### CODE REVIEW

**Comment by ayaankazerouni** [comment]
Thanks! I'll take a look at this soon, but can you change the PR (and future PRs) to be against the `staging` branch?

**Comment by axel1200** [comment]
Would have used the margin class of Bootstrap but Bootstrap 3 does not seem to have such a thing

**Comment by axel1200** [comment]
Old
Screenshot from 2020-08-09 01-16-57
New
Screenshot from 2020-08-09 01-17-31

**Comment by ayaankazerouni** [comment]
Looks good. Can you resolve conflicts with `staging`?

**Comment by s-edwards** [comment]
We should probably find a way to upgrade to a newer version of bootstrap at some point. Unfortunately, the gem we're using for bootstrap no longer appears to be maintained. Instead, we should probably switch to the standard bootstrap gem: https://github.com/twbs/bootstrap-rubygem. I haven't checked what evolution that might require, but it is definitely a switch we need to perform at some point.

**Comment by axel1200** [comment]
It seems BS 4 has only little breaking changes over BS 3

**Comment by ayaankazerouni** [comment]
Merged. Thanks! I created an issue to track the bootstrap upgrade #173

**Pull request merged**
