### PR TITLE
Add LTI v1.1 integration functionality

### PR DESCRIPTION
**Pull request by hosamshahin**

### CODE REVIEW

**Comment by s-edwards** [comment]
Is Ayaan preparing a separate pull request with the revised code?  If so, should I close this one and wait for his to be ready?

**Comment by hosamshahin** [comment]
Yes, you can close this one. @ayaankazerouni, try to pull the latest version and merge it with your codebase. Then when you are ready send your pull request.

**Comment by ayaankazerouni** [comment]
Got it.

**Comment by s-edwards** [comment]
OK, I'm closing this one without merging, and will wait for Ayaan to initiate a new one.  I created a new branch "lti" for this work.  Ayaan, if you could, please create the new pull request against that branch instead of master.  Thanks.

**Comment by ayaankazerouni** [comment]
Will do. I'm finished with most of the other things we talked about, but I
still have the stuff with Workouts and WorkoutOfferings left to deal with.
I'll work on that in India and then open the pull request when I'm done.
Does that sound okay?

On 14 June 2016 at 15:05, Stephen Edwards <notifications@github.com> wrote:

> OK, I'm closing this one without merging, and will wait for Ayaan to
> initiate a new one. I created a new branch "lti" for this work. Ayaan, if
> you could, please create the new pull request against that branch instead
> of master. Thanks.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/web-cat/code-workout/pull/89#issuecomment-225983960>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AKuJZL7wtcZJXS6_PUCeFeSq2vlhcmIxks5qLvtkgaJpZM4IEx5b>
> .
>



-- 
Ayaan Kazerouni
Department of Computer Science
Virginia Tech
770-851-9950

**Comment by s-edwards** [comment]
Sure, no problem.

**Pull request closed without merging**
